### ISSUE TITLE
PROTECTION WARRIOR

### ISSUE THREAD

**Issue by Slamzzz1** [Hemario/Ovale_TankScripts#5]
if there are more than one warrior in group, ovale will show if battle shout is off, you would need to cast again for the script to show for the abilitiy. need to make it so it will recognize if there is a battle shout buff is already up.

**Comment by Hemario** [comment]
Can you check if "full buffs/debuffs scan" is enabled or disabled in Ovale's advanced options? When disabled, Ovale only scans your own buffs. This would explain the behavior you're seeing?

**Comment by Slamzzz1** [comment]
in the options it is not marked, so it needs to be check then to stop the behavior it was doing    On Wednesday, March 13, 2019, 10:56:32 AM CDT, Kevin De Smet <notifications@github.com> wrote:  
 
 
Can you check if "full buffs/debuffs scan" is enabled or disabled in Ovale's advanced options? When disabled, Ovale only scans your own buffs. This would explain the behavior you're seeing?
