### ISSUE TITLE
Errors in Game

### ISSUE THREAD

**Issue by Uggers** [Hemario/Ovale_TankScripts#9]
I keep getting errors for all the class types and azerite neck, the main error looks like this (replacing class with each other class)

`9x ...aceOvale_TankScripts\scripts\deathknight.lua:179: attempt to index local 'OvaleScripts' (a nil value)
...aceOvale_TankScripts\scripts\deathknight.lua:179: in main chunk

Locals:
__Scripts = <table> {
 OvaleScriptsClass = <table> {
 }
 DEFAULT_NAME = "Ovale"
}
OvaleScripts = nil
name = "ovale_tankscripts_deathknight_blood"
desc = "[8.2.0] Ovale_TankScripts: DeathKnight Blood"
code = "Include(ovale_common)
Include(ovale_tankscripts_common)
Include(ovale_deathknight_spells)

AddCheckBox(opt_interrupt L(interrupt) default specialization=blood)
AddCheckBox(opt_dispel L(dispel) default specialization=blood)
AddCheckBox(opt_melee_range L(not_in_melee_range) specialization=blood)
AddCheckBox(opt_use_consumables L(opt_use_consumables) default specialization=blood)

AddFunction BloodPoolingForBoneStorm
{
    Talent(bonestorm_talent) and SpellCooldown(bonestorm) < 3 and Enemies()>=3 and RunicPower() < 100
}

AddFunction BloodDeathStrikeHealing
{
    if (IncomingDamage(5) / 4 > MaxHealth() / 100 * 7) IncomingDamage(5) / 4
    MaxHealth() / 100 * 7
}

AddFunction BloodDefaultShortCDActions
{
    BloodHealMeShortCd()
    if CheckBoxOn(opt_melee_range) and not target.InRange(death_strike) Texture(misc_arrowlup help=L(not_in_melee_range))
    if not BuffPresent(rune_tap_buff) Spell(rune_tap)
}

AddFunction BloodHealMeShortCd
{
    unless(DebuffPresent(healing_immunity_debuff)) 
    {
        if(*temporary) = 80201
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'OvaleScripts' (a nil value)"
`

**Comment by Uggers** [comment]
and the main error being;

`9x Ovale_TankScripts\scripts\common.lua:25: attempt to index local 'OvaleScripts' (a nil value)
Ovale_TankScripts\scripts\common.lua:25: in main chunk

Locals:
__Scripts = <table> {
 OvaleScriptsClass = <table> {
 }
 DEFAULT_NAME = "Ovale"
}
OvaleScripts = nil
name = "ovale_tankscripts_common"
desc = "[8.2.0] Ovale_TankScripts: Common"
code = "Include(ovale_common)

AddFunction AzeriteEssenceMain
{
    Spell(concentrated_flame_essence)
}

AddFunction AzeriteEssenceOffensiveCooldowns
{
    if BuffStacks(lifeblood_buff) < 4 Spell(worldvein_resonance_essence)
}

AddFunction AzeriteEssenceDefensiveCooldowns
{
    Spell(memory_of_lucid_dreams_essence)
}

"
(*temporary) = 80201
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'OvaleScripts' (a nil value)"
`

**Comment by Hemario** [comment]
Did you install Ovale as well?

**Comment by Uggers** [comment]
Yup I have Ovale Spell Priority and Ovale Tank Scripts installed
